FROM python:3.11-slim

WORKDIR /app


COPY . /app

RUN pip install --no-cache-dir -r /app/requirements.txt

ENV PYTHONUNBUFFERED=1
ENV PORT=8501

EXPOSE ${PORT}

CMD ["sh", "-c", "streamlit run streamlit_ui.py \
    --server.port ${PORT} \
    --server.address 0.0.0.0 \
    --server.enableCORS false \
    --server.enableXsrfProtection false \
    --server.headless true \
    --server.enableWebsocketCompression=false"]
